//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeePassRFID.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeePassRFID.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card connection failed..
        /// </summary>
        internal static string CardConnectionFailed {
            get {
                return ResourceManager.GetString("CardConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be empty..
        /// </summary>
        internal static string EmptyPasswordError {
            get {
                return ResourceManager.GetString("EmptyPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeePass RFID Options....
        /// </summary>
        internal static string KeePassRFIDOptions {
            get {
                return ResourceManager.GetString("KeePassRFIDOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap liblogicalaccess_logo_x32 {
            get {
                object obj = ResourceManager.GetObject("liblogicalaccess_logo_x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NFC Tag written..
        /// </summary>
        internal static string NFCTagWritten {
            get {
                return ResourceManager.GetString("NFCTagWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No card inserted..
        /// </summary>
        internal static string NoCardInserted {
            get {
                return ResourceManager.GetString("NoCardInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID chip cannot be retrieved..
        /// </summary>
        internal static string NoChipError {
            get {
                return ResourceManager.GetString("NoChipError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge/Response is unsupported by this chip..
        /// </summary>
        internal static string OTPUnsupported {
            get {
                return ResourceManager.GetString("OTPUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password doesn&apos;t match..
        /// </summary>
        internal static string PasswordMismatchError {
            get {
                return ResourceManager.GetString("PasswordMismatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeePass RFID Error.
        /// </summary>
        internal static string PluginError {
            get {
                return ResourceManager.GetString("PluginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reader connection failed..
        /// </summary>
        internal static string ReaderConnectionFailed {
            get {
                return ResourceManager.GetString("ReaderConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID communication error..
        /// </summary>
        internal static string RFIDCommunicationError {
            get {
                return ResourceManager.GetString("RFIDCommunicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID configuration seems invalid..
        /// </summary>
        internal static string RFIDConfigurationError {
            get {
                return ResourceManager.GetString("RFIDConfigurationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID context cannot be initialized.
        ///Please check that your RFID/NFC reader is properly recognized by the system and LibLogicalAccess middleware installed (http://lla.islog.com)..
        /// </summary>
        internal static string RFIDInitError {
            get {
                return ResourceManager.GetString("RFIDInitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create reader unit..
        /// </summary>
        internal static string RFIDReaderInitError {
            get {
                return ResourceManager.GetString("RFIDReaderInitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified RFID reader cannot be found..
        /// </summary>
        internal static string RFIDReaderNotFound {
            get {
                return ResourceManager.GetString("RFIDReaderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported NFC tag..
        /// </summary>
        internal static string UnsupportedNFCTag {
            get {
                return ResourceManager.GetString("UnsupportedNFCTag", resourceCulture);
            }
        }
    }
}
